"""
BeFaaS Benchmark Results Database Schema
=========================================

This database stores results from load testing experiments comparing different cloud
architectures (FaaS/Lambda, Microservices/ECS, Monolith/ECS) with different authentication
strategies (none, service-integrated, edge).

DATA MODEL OVERVIEW
-------------------

The data flows from a load test experiment as follows:

1. Artillery (load generator) sends HTTP requests to the application
2. The application runs on AWS (Lambda or ECS Fargate)
3. BEFAAS instrumentation logs server-side events
4. CloudWatch captures platform metrics
5. After the experiment, all data is collected and imported here

KEY CONCEPTS
------------

- **Experiment**: A single benchmark run with a specific architecture + auth strategy + hardware config
- **Architecture**: 'faas' (AWS Lambda), 'microservices' (ECS with multiple services), 'monolith' (ECS single service)
- **Auth Strategy**: 'none' (no auth), 'service-integrated' (JWT validation in each handler),
  'service-integrated-manual' (manual JWT), 'edge' (auth at API Gateway/ALB level)
- **x_pair**: Unique request ID generated by Artillery, used to correlate client requests with server events
- **Phase**: Benchmark phases like 'warmup', 'baseline', 'stress' with different load patterns

TABLE RELATIONSHIPS
-------------------

experiments (1) ──┬── (N) requests           # Client-side HTTP requests
                  ├── (N) handler_events     # Server-side handler executions
                  ├── (N) lambda_executions  # Lambda platform metrics (FaaS only)
                  ├── (N) container_starts   # Cold start events
                  ├── (N) rpc_calls          # Inter-service calls
                  ├── (N) phases             # Benchmark phase definitions
                  ├── (N) scaling_rules      # ECS auto-scaling config
                  ├── (1) pricing            # Aggregated cost data
                  ├── (N) pricing_components # Per-function/service costs
                  ├── (N) metrics_ecs        # ECS time-series metrics
                  ├── (N) metrics_alb        # ALB time-series metrics
                  └── (N) edge_auth_events   # Lambda@Edge BEFAAS-EDGE events (edge/edge-selective v2 only)

CORRELATION KEYS
----------------

To trace a request end-to-end:
- requests.x_pair = handler_events.x_pair = rpc_calls.x_pair
- handler_events.lambda_request_id = lambda_executions.request_id = container_starts.lambda_request_id

COMMON QUERIES
--------------

-- Compare latency across architectures:
SELECT architecture, auth_strategy,
       percentile_cont(0.5) WITHIN GROUP (ORDER BY latency_ms) as p50,
       percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms) as p95
FROM requests r JOIN experiments e ON r.experiment_id = e.id
WHERE phase_name = 'baseline' AND NOT is_error
GROUP BY architecture, auth_strategy;

-- Cold start analysis for Lambda:
SELECT function_name, COUNT(*) as cold_starts, AVG(init_duration_ms) as avg_init_ms
FROM lambda_executions WHERE is_cold_start AND experiment_id = ?
GROUP BY function_name;

-- Auth overhead (compare handler duration with/without auth):
SELECT e.auth_strategy, AVG(h.duration_ms) as avg_handler_ms
FROM handler_events h JOIN experiments e ON h.experiment_id = e.id
WHERE h.is_protected_endpoint AND phase_name = 'baseline'
GROUP BY e.auth_strategy;
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional, List

from sqlalchemy import (
    String, Integer, BigInteger, SmallInteger, Boolean, Text,
    Float, Numeric, ForeignKey, Index, UniqueConstraint,
    create_engine, text, delete
)
from sqlalchemy.orm import (
    DeclarativeBase, Mapped, mapped_column, relationship,
    Session
)


class Base(DeclarativeBase):
    """Base class for all models."""
    pass


# =============================================================================
# SCHEMA DOCUMENTATION (AI-readable system documentation)
# =============================================================================

class SchemaDocumentation(Base):
    """
    Documentation table containing detailed descriptions of the database schema,
    system architecture, and usage guidance. Query this table to understand the
    data model without needing access to source code.

    Usage: SELECT * FROM schema_documentation ORDER BY sort_order;
    """
    __tablename__ = "schema_documentation"

    id: Mapped[int] = mapped_column(primary_key=True)
    category: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Documentation category: 'overview', 'table', 'concept', 'query', 'relationship'"
    )
    key: Mapped[str] = mapped_column(
        String(100), nullable=False, unique=True,
        comment="Unique identifier for this documentation entry"
    )
    title: Mapped[str] = mapped_column(
        String(200), nullable=False,
        comment="Human-readable title for this documentation entry"
    )
    content: Mapped[str] = mapped_column(
        Text, nullable=False,
        comment="Detailed documentation content in markdown format"
    )
    sort_order: Mapped[int] = mapped_column(
        Integer, default=0,
        comment="Display order (lower numbers first)"
    )


def populate_schema_documentation(session: Session):
    """Populate the schema_documentation table with system documentation."""

    docs = [
        # === OVERVIEW ===
        {
            "category": "overview",
            "key": "system_purpose",
            "title": "System Purpose",
            "sort_order": 1,
            "content": """
# BeFaaS Benchmark Results Database

This database stores results from **load testing experiments** comparing different cloud architectures and authentication strategies for a web application.

## Research Questions
1. How do different cloud architectures (FaaS vs Microservices vs Monolith) compare in terms of latency, throughput, and cost?
2. What is the performance overhead of different authentication strategies?
3. How do cold starts affect serverless performance?

## Experiment Setup
- **Load Generator**: Artillery sends HTTP requests simulating user traffic
- **Application**: E-commerce-style web app with multiple services (frontend, cart, products, orders, users)
- **Cloud Provider**: AWS (Lambda for FaaS, ECS Fargate for containers)
- **Data Collection**: Client-side metrics, server-side instrumentation, CloudWatch metrics
"""
        },
        {
            "category": "overview",
            "key": "architectures",
            "title": "Cloud Architectures",
            "sort_order": 2,
            "content": """
# Cloud Architectures Compared

## FaaS (Function-as-a-Service)
- **AWS Service**: Lambda
- **Deployment**: Each function deployed separately
- **Scaling**: Automatic, per-request scaling
- **Billing**: Pay per invocation + compute time (GB-seconds)
- **Cold Starts**: New containers initialized on demand
- **Entry Point**: API Gateway -> Lambda functions

## Microservices
- **AWS Service**: ECS Fargate (containers)
- **Deployment**: Multiple services, each in separate containers
- **Scaling**: Auto-scaling based on CPU/request count
- **Billing**: Pay for running container time (vCPU-hours + memory GB-hours)
- **Entry Point**: Application Load Balancer -> ECS services

## Monolith
- **AWS Service**: ECS Fargate (containers)
- **Deployment**: Single service containing all functionality
- **Scaling**: Auto-scaling based on CPU/request count
- **Billing**: Pay for running container time
- **Entry Point**: Application Load Balancer -> single ECS service
"""
        },
        {
            "category": "overview",
            "key": "auth_strategies",
            "title": "Authentication Strategies",
            "sort_order": 3,
            "content": """
# Authentication Strategies Compared

## None (auth_strategy = 'none')
- No authentication required
- Baseline for performance comparison
- All endpoints publicly accessible

## Service-Integrated (auth_strategy = 'service-integrated')
- JWT token validation in each request handler
- Token issued by AWS Cognito
- Validation happens inside the application code
- Adds overhead to each authenticated request

## Service-Integrated Manual (auth_strategy = 'service-integrated-manual')
- Same as service-integrated but with manual JWT validation
- Does not use Cognito SDK for validation
- Lower overhead than SDK-based validation
- Password hashing: argon2id (previously bcrypt for legacy experiments)
- JWT signing: EdDSA / Ed25519 (previously HS256 for legacy experiments)
- See `password_hash_algorithm` and `jwt_sign_algorithm` columns on experiments table

## Edge (auth_strategy = 'edge')
- Authentication at the API Gateway/ALB level
- Requests rejected before reaching application if unauthorized
- Lower application-level overhead but gateway processing cost
"""
        },
        {
            "category": "overview",
            "key": "data_flow",
            "title": "Data Flow",
            "sort_order": 4,
            "content": """
# Data Flow in an Experiment

```
1. BENCHMARK START
   └── Artillery load generator starts sending HTTP requests

2. REQUEST FLOW (for each request)
   ├── Artillery sends request with X-Pair header (correlation ID)
   ├── Request hits API Gateway (FaaS) or ALB (ECS)
   ├── Request routed to appropriate function/service
   ├── Handler processes request, logs BEFAAS events
   ├── Handler may call other functions/services (RPC)
   └── Response returned to Artillery

3. DATA CAPTURED
   ├── requests table: Client-side latency, status, errors
   ├── handler_events table: Server-side processing time
   ├── lambda_executions table: Lambda platform metrics (FaaS only)
   ├── rpc_calls table: Inter-service communication
   └── container_starts table: Cold start events

4. POST-EXPERIMENT
   ├── CloudWatch metrics collected (ECS CPU/memory, ALB stats)
   ├── Pricing calculated based on usage
   └── All data imported into this database
```
"""
        },

        # === KEY CONCEPTS ===
        {
            "category": "concept",
            "key": "correlation_ids",
            "title": "Correlation IDs (x_pair)",
            "sort_order": 10,
            "content": """
# Correlation IDs

## X-Pair Header
Every request from Artillery includes a unique `X-Pair` header value. This ID flows through the entire request lifecycle:

```
requests.x_pair = handler_events.x_pair = rpc_calls.x_pair
```

## Tracing a Request End-to-End

```sql
-- Find client request
SELECT * FROM requests WHERE x_pair = 'abc123';

-- Find corresponding server handler
SELECT * FROM handler_events WHERE x_pair = 'abc123';

-- Find any inter-service calls made during this request
SELECT * FROM rpc_calls WHERE x_pair = 'abc123';
```

## Lambda Request ID
For FaaS experiments, Lambda assigns its own request ID:

```
handler_events.lambda_request_id = lambda_executions.request_id = container_starts.lambda_request_id
```

This allows correlating application-level events with Lambda platform metrics.
"""
        },
        {
            "category": "concept",
            "key": "phases",
            "title": "Benchmark Phases",
            "sort_order": 11,
            "content": """
# Benchmark Phases

Each experiment runs through multiple phases with different load patterns:

## Phase 0: Warmup
- **Purpose**: Initialize cold containers/functions
- **Load**: Low request rate
- **Duration**: Usually 30-60 seconds
- **Analysis**: EXCLUDE from performance comparisons (contains cold start noise)

## Phase 1: Baseline
- **Purpose**: Measure steady-state performance
- **Load**: Constant request rate
- **Duration**: Usually 2-5 minutes
- **Analysis**: USE THIS for fair performance comparisons

## Phase 2+: Stress/Ramp (optional)
- **Purpose**: Test behavior under varying load
- **Load**: Increasing or variable request rates
- **Analysis**: Use for scalability analysis

## Filtering by Phase

```sql
-- Always filter to baseline phase for fair comparisons:
SELECT * FROM requests WHERE phase_name = 'baseline';

-- Or use phase_index:
SELECT * FROM requests WHERE phase_index = 1;
```
"""
        },
        {
            "category": "concept",
            "key": "cold_starts",
            "title": "Cold Starts",
            "sort_order": 12,
            "content": """
# Cold Starts

A cold start occurs when a new container/function instance must be initialized to handle a request.

## Detection Methods

### Lambda (from lambda_executions)
```sql
-- Cold starts have init_duration_ms > 0
SELECT * FROM lambda_executions WHERE is_cold_start = true;
```

### Application-Level (from handler_events)
```sql
-- First request to a new container
SELECT * FROM handler_events WHERE is_cold_start = true;
```

## Cold Start Components (Lambda)
- **init_duration_ms**: Time to initialize the Lambda runtime and load code
- **duration_ms**: Time for handler execution (after initialization)
- **Total cold start latency**: init_duration_ms + duration_ms

## Analyzing Cold Start Impact

```sql
-- Compare latency: cold vs warm requests
SELECT
    is_cold_start,
    COUNT(*) as count,
    AVG(duration_ms) as avg_duration,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms) as p95
FROM handler_events
WHERE experiment_id = ? AND phase_name = 'baseline'
GROUP BY is_cold_start;
```
"""
        },
        {
            "category": "concept",
            "key": "latency_breakdown",
            "title": "Latency Breakdown",
            "sort_order": 13,
            "content": """
# Understanding Latency

## End-to-End Latency (requests.latency_ms)
Total time from client sending request to receiving response. Includes:
- Network latency (client <-> cloud)
- API Gateway / ALB processing
- Handler execution time
- Any inter-service calls

## Handler Duration (handler_events.duration_ms)
Time spent executing application code. Excludes:
- Network latency
- Gateway/LB processing
- Lambda cold start initialization

## Network Overhead
```sql
-- Calculate network/gateway overhead per request
SELECT
    r.x_pair,
    r.latency_ms as total_latency,
    h.duration_ms as handler_time,
    r.latency_ms - h.duration_ms as network_overhead
FROM requests r
JOIN handler_events h ON r.x_pair = h.x_pair AND r.experiment_id = h.experiment_id
WHERE r.experiment_id = ?;
```

## Lambda Platform Overhead (FaaS only)
```sql
-- Compare handler time vs Lambda billed time
SELECT
    h.x_pair,
    h.duration_ms as handler_time,
    l.duration_ms as lambda_duration,
    l.init_duration_ms as cold_start_init
FROM handler_events h
JOIN lambda_executions l ON h.lambda_request_id = l.request_id
WHERE h.experiment_id = ?;
```
"""
        },

        # === TABLE DESCRIPTIONS ===
        {
            "category": "table",
            "key": "table_experiments",
            "title": "Table: experiments",
            "sort_order": 20,
            "content": """
# experiments Table

**Purpose**: Master table containing one row per benchmark experiment run.

## Key Columns
| Column | Description |
|--------|-------------|
| id | Primary key |
| name | Unique experiment name (from directory) |
| architecture | 'faas', 'microservices', or 'monolith' |
| auth_strategy | 'none', 'service-integrated', 'service-integrated-manual', or 'edge' |
| ram_in_mb | Memory allocation (Lambda or Fargate) |
| cpu_in_vcpu | CPU allocation in vCPU (ECS only) |
| run_timestamp | When experiment was executed |

## Common Queries

```sql
-- List all experiments
SELECT id, name, architecture, auth_strategy, ram_in_mb
FROM experiments ORDER BY run_timestamp DESC;

-- Find experiments by architecture
SELECT * FROM experiments WHERE architecture = 'faas';

-- Compare configurations
SELECT architecture, auth_strategy, COUNT(*)
FROM experiments
GROUP BY architecture, auth_strategy;
```
"""
        },
        {
            "category": "table",
            "key": "table_requests",
            "title": "Table: requests",
            "sort_order": 21,
            "content": """
# requests Table

**Purpose**: Client-side HTTP requests from Artillery. PRIMARY TABLE for latency analysis.

## Key Columns
| Column | Description |
|--------|-------------|
| experiment_id | Foreign key to experiments |
| x_pair | Correlation ID (join with handler_events) |
| timestamp_ms | When request was sent (Unix ms) |
| latency_ms | End-to-end response time (ms) |
| endpoint | HTTP endpoint path |
| status_code | HTTP response code |
| is_error | True if request failed |
| is_timeout | True if request timed out |
| phase_name | Benchmark phase ('warmup', 'baseline', etc.) |

## Common Queries

```sql
-- Latency percentiles for an experiment
SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY latency_ms) as p50,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms) as p95,
    percentile_cont(0.99) WITHIN GROUP (ORDER BY latency_ms) as p99
FROM requests
WHERE experiment_id = ? AND phase_name = 'baseline' AND NOT is_error;

-- Error rate
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE is_error) as errors,
    ROUND(100.0 * COUNT(*) FILTER (WHERE is_error) / COUNT(*), 2) as error_pct
FROM requests WHERE experiment_id = ?;

-- Throughput over time
SELECT
    (timestamp_ms / 1000) as second,
    COUNT(*) as requests_per_second
FROM requests WHERE experiment_id = ?
GROUP BY (timestamp_ms / 1000) ORDER BY second;
```
"""
        },
        {
            "category": "table",
            "key": "table_handler_events",
            "title": "Table: handler_events",
            "sort_order": 22,
            "content": """
# handler_events Table

**Purpose**: Server-side handler execution from BEFAAS instrumentation.

## Key Columns
| Column | Description |
|--------|-------------|
| experiment_id | Foreign key to experiments |
| x_pair | Correlation ID (join with requests) |
| lambda_request_id | Lambda request ID (join with lambda_executions) |
| function_name | 'frontend', 'cart', 'products', 'orders', 'users' |
| route | HTTP route (e.g., 'GET /api/cart') |
| duration_ms | Handler execution time (ms) |
| is_cold_start | True if first request to this instance |
| status_code | HTTP response code |

## Common Queries

```sql
-- Handler duration by function
SELECT
    function_name,
    AVG(duration_ms) as avg_ms,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms) as p95_ms
FROM handler_events
WHERE experiment_id = ? AND phase_name = 'baseline'
GROUP BY function_name;

-- Cold start impact
SELECT
    is_cold_start,
    COUNT(*) as count,
    AVG(duration_ms) as avg_duration
FROM handler_events WHERE experiment_id = ?
GROUP BY is_cold_start;

-- Join with requests for full picture
SELECT
    r.latency_ms as client_latency,
    h.duration_ms as handler_time,
    r.latency_ms - h.duration_ms as overhead
FROM requests r
JOIN handler_events h ON r.x_pair = h.x_pair AND r.experiment_id = h.experiment_id
WHERE r.experiment_id = ? AND r.phase_name = 'baseline';
```
"""
        },
        {
            "category": "table",
            "key": "table_lambda_executions",
            "title": "Table: lambda_executions",
            "sort_order": 23,
            "content": """
# lambda_executions Table

**Purpose**: Lambda platform metrics from CloudWatch REPORT logs. **FaaS only**.

## Key Columns
| Column | Description |
|--------|-------------|
| experiment_id | Foreign key to experiments |
| request_id | Lambda Request ID (join with handler_events.lambda_request_id) |
| function_name | Lambda function name |
| duration_ms | Actual execution time |
| billed_duration_ms | Billable duration (rounded up) |
| init_duration_ms | Cold start initialization time |
| memory_size_mb | Configured memory |
| max_memory_used_mb | Peak memory usage |
| is_cold_start | True if init_duration_ms > 0 |

## Common Queries

```sql
-- Cold start analysis
SELECT
    function_name,
    COUNT(*) FILTER (WHERE is_cold_start) as cold_starts,
    COUNT(*) as total,
    AVG(init_duration_ms) FILTER (WHERE is_cold_start) as avg_init_ms
FROM lambda_executions WHERE experiment_id = ?
GROUP BY function_name;

-- Memory efficiency
SELECT
    function_name,
    memory_size_mb as configured,
    AVG(max_memory_used_mb) as avg_used,
    MAX(max_memory_used_mb) as max_used
FROM lambda_executions WHERE experiment_id = ?
GROUP BY function_name, memory_size_mb;

-- Billable compute
SELECT
    function_name,
    SUM(billed_duration_ms) / 1000.0 as total_seconds,
    SUM(billed_duration_ms) / 1000.0 * memory_size_mb / 1024.0 as gb_seconds
FROM lambda_executions WHERE experiment_id = ?
GROUP BY function_name, memory_size_mb;
```
"""
        },
        {
            "category": "table",
            "key": "table_rpc_calls",
            "title": "Table: rpc_calls",
            "sort_order": 24,
            "content": """
# rpc_calls Table

**Purpose**: Inter-service calls within a request (e.g., frontend -> cart).

## Key Columns
| Column | Description |
|--------|-------------|
| experiment_id | Foreign key to experiments |
| direction | 'out' (caller) or 'in' (callee) |
| x_pair | Parent request correlation ID |
| function_name | Function logging this event |
| target_function | For 'out': function being called |
| call_x_pair | For 'out': correlation ID of the downstream call |
| duration_ms | For 'out': round-trip time |
| is_cold_start | For 'in': whether call triggered cold start |

## Common Queries

```sql
-- Call graph: who calls whom
SELECT
    function_name as caller,
    target_function as callee,
    COUNT(*) as call_count,
    AVG(duration_ms) as avg_latency
FROM rpc_calls
WHERE experiment_id = ? AND direction = 'out'
GROUP BY function_name, target_function;

-- Inter-service latency
SELECT
    target_function,
    AVG(duration_ms) as avg_ms,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms) as p95_ms
FROM rpc_calls
WHERE experiment_id = ? AND direction = 'out'
GROUP BY target_function;

-- Trace a request through services
SELECT direction, function_name, target_function, duration_ms
FROM rpc_calls
WHERE x_pair = 'abc123'
ORDER BY timestamp_ms;
```
"""
        },
        {
            "category": "table",
            "key": "table_pricing",
            "title": "Table: pricing",
            "sort_order": 25,
            "content": """
# pricing Table

**Purpose**: Aggregated cost data per experiment.

## Key Columns (FaaS)
| Column | Description |
|--------|-------------|
| lambda_total_invocations | Total Lambda calls |
| lambda_total_gb_seconds | Compute usage |
| lambda_total_cost | Lambda cost ($) |
| api_gw_cost | API Gateway cost ($) |

## Key Columns (ECS)
| Column | Description |
|--------|-------------|
| fargate_total_cost | Fargate container cost ($) |
| alb_total_cost | Load balancer cost ($) |

## Key Columns (Common)
| Column | Description |
|--------|-------------|
| redis_total_cost | Redis/ElastiCache cost ($) |
| cognito_cost | Cognito auth cost ($) |

## Common Queries

```sql
-- Total cost by experiment
SELECT
    e.name,
    e.architecture,
    COALESCE(p.lambda_total_cost, 0) + COALESCE(p.api_gw_cost, 0) +
    COALESCE(p.fargate_total_cost, 0) + COALESCE(p.alb_total_cost, 0) +
    COALESCE(p.redis_total_cost, 0) as total_cost
FROM experiments e
LEFT JOIN pricing p ON e.id = p.experiment_id;

-- Cost comparison by architecture
SELECT
    e.architecture,
    AVG(COALESCE(p.lambda_total_cost, 0) + COALESCE(p.fargate_total_cost, 0)) as avg_compute_cost
FROM experiments e
LEFT JOIN pricing p ON e.id = p.experiment_id
GROUP BY e.architecture;
```
"""
        },

        # === COMMON ANALYSIS QUERIES ===
        {
            "category": "query",
            "key": "query_compare_architectures",
            "title": "Query: Compare Architectures",
            "sort_order": 30,
            "content": """
# Comparing Architectures

## Latency Comparison

```sql
SELECT
    e.architecture,
    e.auth_strategy,
    COUNT(*) as request_count,
    ROUND(AVG(r.latency_ms)::numeric, 2) as avg_ms,
    ROUND(percentile_cont(0.5) WITHIN GROUP (ORDER BY r.latency_ms)::numeric, 2) as p50_ms,
    ROUND(percentile_cont(0.95) WITHIN GROUP (ORDER BY r.latency_ms)::numeric, 2) as p95_ms,
    ROUND(percentile_cont(0.99) WITHIN GROUP (ORDER BY r.latency_ms)::numeric, 2) as p99_ms
FROM requests r
JOIN experiments e ON r.experiment_id = e.id
WHERE r.phase_name = 'baseline' AND NOT r.is_error
GROUP BY e.architecture, e.auth_strategy
ORDER BY e.architecture, e.auth_strategy;
```

## Error Rate Comparison

```sql
SELECT
    e.architecture,
    e.auth_strategy,
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE r.is_error) as errors,
    ROUND(100.0 * COUNT(*) FILTER (WHERE r.is_error) / COUNT(*), 2) as error_pct
FROM requests r
JOIN experiments e ON r.experiment_id = e.id
WHERE r.phase_name = 'baseline'
GROUP BY e.architecture, e.auth_strategy;
```

## Cost Comparison

```sql
SELECT
    e.architecture,
    e.auth_strategy,
    ROUND(AVG(COALESCE(p.lambda_total_cost, 0) + COALESCE(p.api_gw_cost, 0) +
              COALESCE(p.fargate_total_cost, 0) + COALESCE(p.alb_total_cost, 0))::numeric, 4) as avg_compute_cost
FROM experiments e
LEFT JOIN pricing p ON e.id = p.experiment_id
GROUP BY e.architecture, e.auth_strategy;
```
"""
        },
        {
            "category": "query",
            "key": "query_auth_overhead",
            "title": "Query: Authentication Overhead",
            "sort_order": 31,
            "content": """
# Measuring Authentication Overhead

## Handler-Level Comparison

```sql
-- Compare handler duration with and without auth
SELECT
    e.auth_strategy,
    AVG(h.duration_ms) as avg_handler_ms,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY h.duration_ms) as p50_ms,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY h.duration_ms) as p95_ms
FROM handler_events h
JOIN experiments e ON h.experiment_id = e.id
WHERE h.phase_name = 'baseline'
  AND e.architecture = 'faas'  -- Compare within same architecture
GROUP BY e.auth_strategy;
```

## End-to-End Latency Impact

```sql
-- Compare client latency
SELECT
    e.auth_strategy,
    AVG(r.latency_ms) as avg_latency_ms,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY r.latency_ms) as p95_ms
FROM requests r
JOIN experiments e ON r.experiment_id = e.id
WHERE r.phase_name = 'baseline' AND NOT r.is_error
  AND e.architecture = 'faas'
GROUP BY e.auth_strategy;
```

## Calculate Overhead

```sql
-- Calculate auth overhead vs baseline (none)
WITH baseline AS (
    SELECT AVG(r.latency_ms) as avg_latency
    FROM requests r
    JOIN experiments e ON r.experiment_id = e.id
    WHERE e.auth_strategy = 'none' AND r.phase_name = 'baseline' AND NOT r.is_error
)
SELECT
    e.auth_strategy,
    AVG(r.latency_ms) as avg_latency,
    AVG(r.latency_ms) - (SELECT avg_latency FROM baseline) as overhead_ms
FROM requests r
JOIN experiments e ON r.experiment_id = e.id
WHERE r.phase_name = 'baseline' AND NOT r.is_error
GROUP BY e.auth_strategy;
```
"""
        },
        {
            "category": "query",
            "key": "query_cold_start_analysis",
            "title": "Query: Cold Start Analysis",
            "sort_order": 32,
            "content": """
# Cold Start Analysis

## Cold Start Frequency (Lambda)

```sql
SELECT
    e.name,
    COUNT(*) FILTER (WHERE l.is_cold_start) as cold_starts,
    COUNT(*) as total_invocations,
    ROUND(100.0 * COUNT(*) FILTER (WHERE l.is_cold_start) / COUNT(*), 2) as cold_start_pct
FROM lambda_executions l
JOIN experiments e ON l.experiment_id = e.id
WHERE e.architecture = 'faas'
GROUP BY e.name;
```

## Cold Start Duration by Function

```sql
SELECT
    function_name,
    COUNT(*) FILTER (WHERE is_cold_start) as cold_starts,
    ROUND(AVG(init_duration_ms) FILTER (WHERE is_cold_start)::numeric, 2) as avg_init_ms,
    ROUND(MAX(init_duration_ms)::numeric, 2) as max_init_ms
FROM lambda_executions
WHERE experiment_id = ?
GROUP BY function_name
HAVING COUNT(*) FILTER (WHERE is_cold_start) > 0;
```

## Cold Start Impact on Latency

```sql
SELECT
    h.is_cold_start,
    COUNT(*) as count,
    ROUND(AVG(h.duration_ms)::numeric, 2) as avg_handler_ms,
    ROUND(AVG(r.latency_ms)::numeric, 2) as avg_client_latency_ms
FROM handler_events h
JOIN requests r ON h.x_pair = r.x_pair AND h.experiment_id = r.experiment_id
WHERE h.experiment_id = ? AND h.phase_name = 'baseline'
GROUP BY h.is_cold_start;
```

## Cold Starts Over Time

```sql
SELECT
    (timestamp_ms / 60000) as minute,
    COUNT(*) FILTER (WHERE is_cold_start) as cold_starts
FROM lambda_executions
WHERE experiment_id = ?
GROUP BY (timestamp_ms / 60000)
ORDER BY minute;
```
"""
        },
    ]

    # Clear existing documentation
    session.execute(delete(SchemaDocumentation))

    # Insert documentation entries
    for doc in docs:
        session.add(SchemaDocumentation(**doc))

    session.commit()


# =============================================================================
# EXPERIMENT (Master Table)
# =============================================================================

class Experiment(Base):
    """
    Master table for benchmark experiments. One row per experiment run.

    An experiment represents a single benchmark execution with a specific:
    - Architecture (faas, microservices, monolith)
    - Authentication strategy (none, service-integrated, edge)
    - Hardware configuration (RAM, CPU, scaling rules)

    The experiment name follows the pattern:
    {architecture}_{auth_strategy}_{ram}MB_{workload}_{timestamp}
    Example: faas_service-integrated_512MB_minimal_2026-01-10T14-04-00-138Z

    Use this table to:
    - Filter experiments by architecture/auth for comparison
    - Get hardware config and pricing metadata
    - Join with other tables using experiment_id
    """
    __tablename__ = "experiments"
    __table_args__ = (
        Index("idx_exp_arch", "architecture"),
        Index("idx_exp_auth", "auth_strategy"),
        Index("idx_exp_arch_auth", "architecture", "auth_strategy"),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True,
        comment="Auto-incrementing primary key"
    )
    name: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False,
        comment="Unique experiment name from directory, e.g. faas_none_512MB_minimal_2026-01-09T22-48-43-424Z"
    )

    # === From directory name parsing ===
    architecture: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Cloud architecture: 'faas' (Lambda), 'microservices' (ECS multi-service), 'monolith' (ECS single-service)"
    )
    auth_strategy: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Authentication method: 'none', 'service-integrated' (JWT in handler), 'service-integrated-manual', 'edge' (auth at gateway), 'edge-selective' (Lambda@Edge only for protected paths)"
    )
    run_timestamp: Mapped[Optional[datetime]] = mapped_column(
        comment="When the experiment was executed, parsed from directory name timestamp"
    )

    # === From hardware_config.json ===
    aws_service: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS service used: 'lambda' for FaaS, 'fargate' for ECS-based architectures"
    )
    ram_in_mb: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Memory allocation in MB. For Lambda: function memory. For Fargate: container memory."
    )
    bundle_mode: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="FaaS only: How functions are packaged - 'individual' (one per function) or 'shared' (bundled)"
    )
    cpu_in_vcpu: Mapped[Optional[float]] = mapped_column(
        Numeric(4, 2),
        comment="ECS only: CPU allocation in vCPU units (e.g., 0.25, 0.5, 1.0, 2.0)"
    )
    cpu_units: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="ECS only: CPU in AWS CPU units (256=0.25 vCPU, 512=0.5, 1024=1.0, etc.)"
    )
    # === Algorithm fields (service-integrated-manual auth) ===
    password_hash_algorithm: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Password hashing algorithm: 'bcrypt' (legacy) or 'argon2id' (current). Only for service-integrated-manual auth."
    )
    jwt_sign_algorithm: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="JWT signing algorithm: 'HS256' (legacy) or 'EdDSA' (current). Only for service-integrated-manual auth."
    )
    with_cloudfront: Mapped[Optional[bool]] = mapped_column(
        Boolean, default=False,
        comment="Whether CloudFront was deployed as passthrough proxy (--with-cloudfront flag). True for edge/edge-selective (implicit) and explicit proxy deployments."
    )

    # === From benchmark_configuration.json ===
    http_timeout_seconds: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="HTTP request timeout in seconds used by Artillery load generator"
    )

    # === From experiment_start_time.txt ===
    start_timestamp_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Unix timestamp in milliseconds when infrastructure deployment completed and benchmark started"
    )

    # === Computed during import ===
    benchmark_start_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Unix timestamp (ms) of the first request in the benchmark (computed from requests table)"
    )
    benchmark_end_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Unix timestamp (ms) of the last request in the benchmark (computed from requests table)"
    )

    # === From pricing/pricing.json metadata ===
    pricing_region: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="AWS region for pricing calculations, e.g. 'eu-central-1'"
    )
    pricing_start_time: Mapped[Optional[datetime]] = mapped_column(
        comment="Start time of the pricing calculation window"
    )
    pricing_end_time: Mapped[Optional[datetime]] = mapped_column(
        comment="End time of the pricing calculation window"
    )
    pricing_duration_minutes: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Duration of the benchmark in minutes for cost calculation"
    )
    pricing_duration_hours: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Duration of the benchmark in hours for cost calculation"
    )
    pricing_collected_at: Mapped[Optional[datetime]] = mapped_column(
        comment="When pricing data was collected from AWS Cost Explorer"
    )

    # === From error_description.md ===
    error_description: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="Human-written notes about any issues or anomalies during this experiment"
    )

    created_at: Mapped[datetime] = mapped_column(
        default=datetime.now,
        comment="When this record was imported into the database"
    )

    # === Relationships ===
    scaling_rules: Mapped[List["ScalingRule"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    phases: Mapped[List["Phase"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    requests: Mapped[List["Request"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    lambda_executions: Mapped[List["LambdaExecution"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    handler_events: Mapped[List["HandlerEvent"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    container_starts: Mapped[List["ContainerStart"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    rpc_calls: Mapped[List["RpcCall"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    pricing: Mapped[Optional["Pricing"]] = relationship(back_populates="experiment", cascade="all, delete-orphan", uselist=False)
    pricing_components: Mapped[List["PricingComponent"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    metrics_ecs: Mapped[List["MetricsEcs"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    metrics_alb: Mapped[List["MetricsAlb"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")
    edge_auth_events: Mapped[List["EdgeAuthEvent"]] = relationship(back_populates="experiment", cascade="all, delete-orphan")


# =============================================================================
# SCALING RULES (ECS auto-scaling configuration)
# =============================================================================

class ScalingRule(Base):
    """
    Per-service auto-scaling rules configuration.

    Only populated for microservices/monolith architectures running on ECS Fargate.
    Each row describes one scaling rule for one service. A service can have multiple
    rules (e.g., CPU-based and request-count-based scaling).

    For monolith: service_name = 'monolith'
    For microservices: service_name = 'frontend-service', 'product-service', etc.

    Common rule types:
    - 'cpu': Scale based on average CPU utilization percentage
    - 'request_count': Scale based on ALB requests per target per minute

    Example: Get scaling config for all services in an experiment
    SELECT service_name, rule_type, target_value, min_capacity, max_capacity
    FROM scaling_rules
    WHERE experiment_id = ?
    ORDER BY service_name, rule_type;
    """
    __tablename__ = "scaling_rules"
    __table_args__ = (
        UniqueConstraint("experiment_id", "service_name", "rule_type"),
        Index("idx_scaling_exp", "experiment_id"),
        Index("idx_scaling_exp_svc", "experiment_id", "service_name"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )
    service_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="ECS service name: 'monolith', 'frontend-service', 'product-service', 'cart-service', 'order-service', 'content-service'"
    )
    rule_type: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="Scaling metric type: 'cpu' (CPU utilization target) or 'request_count' (ALB requests per target per minute)"
    )
    target_value: Mapped[int] = mapped_column(
        Integer, nullable=False,
        comment="Target value for the metric (e.g., 70 for 70% CPU, 2500 for requests/target/min)"
    )
    min_capacity: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Minimum number of running tasks for this service"
    )
    max_capacity: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Maximum number of running tasks for this service"
    )
    cpu_units: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="CPU units for this service (256=0.25 vCPU, 512=0.5, 1024=1.0)"
    )
    memory_mb: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Memory in MB for this service"
    )
    scale_in_cooldown_sec: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Seconds to wait after scale-in before another scale-in can occur"
    )
    scale_out_cooldown_sec: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Seconds to wait after scale-out before another scale-out can occur"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="scaling_rules")


# =============================================================================
# PHASES (Benchmark load phases)
# =============================================================================

class Phase(Base):
    """
    Benchmark phases define different load patterns during the experiment.

    A typical benchmark has multiple phases:
    - Phase 0: 'warmup' - Low load to initialize cold containers/functions
    - Phase 1: 'baseline' - Steady-state load for performance measurement
    - Phase 2+: 'stress', 'ramp', etc. - Variable load patterns

    Each request and handler_event is tagged with its phase, allowing
    analysis of performance under different load conditions.

    Use phase_name='baseline' for fair performance comparisons between experiments.
    """
    __tablename__ = "phases"
    __table_args__ = (
        UniqueConstraint("experiment_id", "phase_index"),
        Index("idx_phase_exp", "experiment_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )
    phase_index: Mapped[int] = mapped_column(
        SmallInteger, nullable=False,
        comment="Zero-based index of the phase in execution order (0=first phase)"
    )
    phase_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="Human-readable phase name: 'warmup', 'baseline', 'stress', 'ramp', etc."
    )
    duration_seconds: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Configured duration of this phase in seconds"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="phases")


# =============================================================================
# REQUESTS (Client-side HTTP requests from Artillery)
# =============================================================================

class Request(Base):
    """
    Client-side HTTP requests captured by Artillery load generator.

    This is the PRIMARY TABLE for latency analysis from the user's perspective.
    Each row represents one HTTP request sent by Artillery to the application.

    KEY FIELDS:
    - latency_ms: End-to-end response time as seen by the client (includes network)
    - is_error/is_timeout: Whether the request failed
    - x_pair: Correlation ID to join with handler_events for server-side data

    LATENCY BREAKDOWN (when joined with handler_events):
    - latency_ms = network_overhead_ms + handler_duration_ms
    - network_overhead_ms = latency_ms - handler_duration_ms (computed)

    COMMON ANALYSIS:
    - Percentile latencies: p50, p95, p99 of latency_ms
    - Error rates: COUNT(*) WHERE is_error / COUNT(*)
    - Throughput: COUNT(*) per second
    - Compare by endpoint, auth_type, phase

    Filter by phase_name='baseline' for steady-state performance comparisons.
    """
    __tablename__ = "requests"
    __table_args__ = (
        Index("idx_req_exp", "experiment_id"),
        Index("idx_req_exp_ts", "experiment_id", "timestamp_ms"),
        Index("idx_req_exp_endpoint", "experiment_id", "endpoint"),
        Index("idx_req_exp_auth", "experiment_id", "auth_type"),
        Index("idx_req_exp_phase", "experiment_id", "phase_index"),
        Index("idx_req_xpair", "x_pair"),
        Index("idx_req_latency", "experiment_id", "latency_ms"),
        # Composite indexes for JOIN optimization - performance improvement
        Index("idx_req_exp_xpair", "experiment_id", "x_pair"),
        Index("idx_req_exp_context", "experiment_id", "context_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    # === Correlation IDs ===
    x_pair: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Unique request ID (X-Pair header) to correlate with handler_events and rpc_calls"
    )
    context_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="User session context ID for tracking requests within a virtual user session"
    )

    # === Timing ===
    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp in milliseconds when the request was sent"
    )
    latency_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="End-to-end response time in milliseconds (client perspective, includes network latency)"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start (timestamp_ms - benchmark_start_ms)"
    )
    phase_relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since the current phase started"
    )

    # === Request details ===
    endpoint: Mapped[Optional[str]] = mapped_column(
        String(200),
        comment="HTTP endpoint path, e.g. '/api/cart', '/api/products/{id}'"
    )
    status_code: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="HTTP response status code (200, 401, 500, etc.). NULL if request timed out."
    )
    auth_type: Mapped[Optional[str]] = mapped_column(
        String(30),
        comment="Authentication type used: 'none', 'bearer', 'cognito', 'service-integrated-manual'. Derived from endpoint protection."
    )

    # === Error tracking ===
    is_error: Mapped[bool] = mapped_column(
        Boolean, default=False,
        comment="True if request failed (non-2xx status, timeout, or connection error)"
    )
    is_timeout: Mapped[bool] = mapped_column(
        Boolean, default=False,
        comment="True if request exceeded http_timeout_seconds and was aborted"
    )
    error_type: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Error category: 'timeout', 'connection_refused', 'http_error', etc."
    )
    error_code: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Specific error code: 'ETIMEDOUT', 'ECONNREFUSED', etc."
    )

    # === Phase information ===
    phase_index: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Zero-based index of the benchmark phase when this request was made"
    )
    phase_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="Name of the benchmark phase: 'warmup', 'baseline', 'stress', etc."
    )

    # === Computed fields (populated by joining with handler_events) ===
    handler_duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Server-side handler execution time from handler_events (matched by x_pair)"
    )
    network_overhead_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Network latency = latency_ms - handler_duration_ms. Includes API Gateway/ALB overhead."
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="requests")


# =============================================================================
# LAMBDA EXECUTIONS (AWS Lambda platform metrics)
# =============================================================================

class LambdaExecution(Base):
    """
    Lambda platform metrics from CloudWatch REPORT log lines.

    ONLY POPULATED FOR FaaS ARCHITECTURE (architecture='faas').

    Each row represents one Lambda function invocation as reported by AWS.
    This is the authoritative source for:
    - Billed duration (what you pay for)
    - Memory usage
    - Cold start initialization time

    KEY FIELDS:
    - duration_ms: Actual execution time
    - billed_duration_ms: Rounded up to nearest 1ms (what AWS charges)
    - init_duration_ms: Cold start initialization time (only present on cold starts)
    - is_cold_start: True if init_duration_ms > 0

    COLD START ANALYSIS:
    SELECT function_name,
           COUNT(*) FILTER (WHERE is_cold_start) as cold_starts,
           AVG(init_duration_ms) FILTER (WHERE is_cold_start) as avg_init_ms
    FROM lambda_executions WHERE experiment_id = ?
    GROUP BY function_name;

    COST ANALYSIS:
    - Lambda cost = (billed_duration_ms / 1000) * memory_size_mb / 1024 * price_per_gb_second
    - See pricing table for actual computed costs
    """
    __tablename__ = "lambda_executions"
    __table_args__ = (
        Index("idx_lambda_exp", "experiment_id"),
        Index("idx_lambda_exp_fn", "experiment_id", "function_name"),
        Index("idx_lambda_exp_cold", "experiment_id", "is_cold_start"),
        Index("idx_lambda_reqid", "request_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    request_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS Lambda Request ID (unique per invocation). Use to correlate with handler_events.lambda_request_id"
    )
    function_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Lambda function name: 'frontend', 'cart', 'products', 'orders', 'users', etc."
    )

    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp (ms) when the REPORT log was emitted (end of invocation)"
    )
    duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Actual execution duration in milliseconds"
    )
    billed_duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Billed duration in milliseconds (rounded up, minimum 1ms). This is what AWS charges for."
    )
    init_duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Cold start initialization time in ms. Only present when is_cold_start=True. Includes loading code, initializing runtime."
    )

    memory_size_mb: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Configured Lambda memory in MB (128-10240)"
    )
    max_memory_used_mb: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Peak memory used during this invocation in MB"
    )

    is_cold_start: Mapped[bool] = mapped_column(
        Boolean, default=False,
        comment="True if this invocation required container initialization (init_duration_ms > 0)"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="lambda_executions")


# =============================================================================
# HANDLER EVENTS (Server-side handler execution)
# =============================================================================

class HandlerEvent(Base):
    """
    Server-side handler execution metrics from BEFAAS instrumentation.

    POPULATED FOR ALL ARCHITECTURES (faas, microservices, monolith).

    Each row represents one HTTP request as processed by the application handler.
    This captures the actual business logic execution time, excluding:
    - Network latency
    - API Gateway / ALB processing
    - Lambda cold start (captured separately)

    KEY FIELDS:
    - duration_ms: Time spent in the handler function (business logic)
    - is_cold_start: Application-level cold start detection
    - x_pair: Correlation ID to join with requests table

    CORRELATION:
    - Join with requests ON x_pair to get: network_overhead = requests.latency_ms - handler_events.duration_ms
    - Join with lambda_executions ON lambda_request_id for Lambda platform metrics

    AUTH OVERHEAD ANALYSIS:
    Compare handler duration_ms between auth_strategy='none' and 'service-integrated'
    for the same endpoint to measure authentication overhead.
    """
    __tablename__ = "handler_events"
    __table_args__ = (
        Index("idx_handler_exp", "experiment_id"),
        Index("idx_handler_exp_fn", "experiment_id", "function_name"),
        Index("idx_handler_xpair", "x_pair"),
        Index("idx_handler_exp_auth", "experiment_id", "auth_type"),
        # Composite indexes for JOIN optimization - performance improvement
        Index("idx_handler_exp_xpair", "experiment_id", "x_pair"),
        Index("idx_handler_exp_context", "experiment_id", "context_id"),
        Index("idx_handler_exp_phase_idx", "experiment_id", "phase_index"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    # === Correlation IDs ===
    x_pair: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Request correlation ID (X-Pair header). Join with requests.x_pair for end-to-end analysis."
    )
    context_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="User session context ID"
    )
    lambda_request_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS Lambda Request ID. Join with lambda_executions.request_id for platform metrics. NULL for ECS."
    )

    # === Handler details ===
    function_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Function/service name: 'frontend', 'cart', 'products', 'orders', 'users'"
    )
    route: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="HTTP route pattern, e.g. 'GET /api/cart', 'POST /api/orders'"
    )
    status_code: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="HTTP response status code returned by the handler"
    )
    is_cold_start: Mapped[bool] = mapped_column(
        Boolean, default=False,
        comment="True if this was the first request to this container/function instance (application-level detection)"
    )
    request_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Number of requests this container has processed (used for cold start detection)"
    )

    # === Timing ===
    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp (ms) when the handler started processing"
    )
    duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Handler execution time in milliseconds (business logic only, excludes network/platform overhead)"
    )

    # === Context ===
    auth_type: Mapped[Optional[str]] = mapped_column(
        String(30),
        comment="Authentication type: 'none', 'bearer', 'cognito', 'service-integrated-manual'"
    )
    phase_index: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Benchmark phase index (0-based)"
    )
    phase_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="Benchmark phase name: 'warmup', 'baseline', 'stress'"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start"
    )
    phase_relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since current phase started"
    )

    is_protected_endpoint: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        comment="True if this endpoint requires authentication (useful for auth overhead analysis)"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="handler_events")


# =============================================================================
# CONTAINER STARTS (Cold start events)
# =============================================================================

class ContainerStart(Base):
    """
    Container/function cold start events from BEFAAS instrumentation.

    Records the first request to each new container/Lambda instance.
    Use this to analyze cold start frequency and distribution over time.

    For Lambda: correlate with lambda_executions using lambda_request_id
    to get platform-level init_duration_ms.
    """
    __tablename__ = "container_starts"
    __table_args__ = (
        Index("idx_cold_exp", "experiment_id"),
        Index("idx_cold_exp_fn", "experiment_id", "function_name"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    lambda_request_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS Lambda Request ID for correlation with lambda_executions"
    )
    function_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Function/service name that experienced the cold start"
    )
    deployment_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Unique identifier for this container/function instance"
    )

    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp (ms) when the cold start was detected"
    )
    container_start_time_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Unix timestamp (ms) when the container started initializing"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="container_starts")


# =============================================================================
# RPC CALLS (Inter-service communication)
# =============================================================================

class RpcCall(Base):
    """
    Inter-function/service calls within a single user request.

    When a frontend function calls a backend function (e.g., frontend -> cart),
    this is recorded as an RPC call. Used to analyze:
    - Call graph and service dependencies
    - Inter-service latency
    - Cascading failures

    DIRECTION FIELD:
    - 'out': Outgoing call from caller's perspective (has duration_ms, target_function)
    - 'in': Incoming call from callee's perspective (has is_cold_start, received_at_ms)

    CORRELATION:
    - call_x_pair: The x_pair of the downstream call (use to find the callee's handler_event)
    - x_pair: The x_pair of the parent request context

    CALL CHAIN ANALYSIS:
    To trace: User -> Frontend -> Cart -> Products
    1. Find request with endpoint='/api/cart/add'
    2. Find handler_event with matching x_pair (frontend handler)
    3. Find rpc_call with direction='out' and x_pair matching
    4. Follow call_x_pair to find the cart handler_event
    """
    __tablename__ = "rpc_calls"
    __table_args__ = (
        Index("idx_rpc_exp", "experiment_id"),
        Index("idx_rpc_exp_dir", "experiment_id", "direction"),
        Index("idx_rpc_exp_fn", "experiment_id", "function_name"),
        Index("idx_rpc_xpair", "x_pair"),
        # Composite indexes for JOIN optimization - performance improvement
        Index("idx_rpc_exp_xpair", "experiment_id", "x_pair"),
        Index("idx_rpc_exp_context", "experiment_id", "context_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    direction: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="'out' = outgoing call (caller side), 'in' = incoming call (callee side)"
    )

    # === Correlation IDs ===
    x_pair: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="Parent request's correlation ID"
    )
    context_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="User session context ID"
    )
    lambda_request_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS Lambda Request ID of the function making/receiving the call"
    )

    # === Call details ===
    function_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Name of the function logging this event (caller for 'out', callee for 'in')"
    )
    target_function: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="For direction='out': name of the function being called"
    )
    call_x_pair: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="For direction='out': the x_pair assigned to this downstream call (use to find callee's handler_event)"
    )

    call_type: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="Type of call: 'http', 'invoke' (Lambda direct invoke), etc."
    )
    duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="For direction='out': round-trip time of the call in milliseconds"
    )
    success: Mapped[bool] = mapped_column(
        Boolean, default=True,
        comment="Whether the call succeeded"
    )
    is_cold_start: Mapped[bool] = mapped_column(
        Boolean, default=False,
        comment="For direction='in': whether this call triggered a cold start in the callee"
    )

    # === Timing ===
    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp (ms) when the call was initiated (out) or received (in)"
    )
    received_at_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="For direction='in': Unix timestamp (ms) when the call was received"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start"
    )

    # === Context ===
    auth_type: Mapped[Optional[str]] = mapped_column(
        String(30),
        comment="Authentication type used for this call"
    )
    phase_index: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Benchmark phase index"
    )
    phase_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="Benchmark phase name"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="rpc_calls")


# =============================================================================
# PRICING (Aggregated cost data)
# =============================================================================

class Pricing(Base):
    """
    Aggregated pricing/cost data for an experiment.

    One row per experiment containing total costs broken down by service:
    - Lambda: Request costs + compute (GB-seconds) costs
    - API Gateway: Per-request costs
    - Fargate: vCPU-hours + memory GB-hours
    - ALB: Hourly + LCU (capacity unit) costs
    - Redis: Hourly instance costs
    - Cognito: Monthly active user costs

    COST COMPARISON:
    To compare costs between architectures:
    SELECT e.architecture, e.auth_strategy,
           COALESCE(p.lambda_total_cost, 0) + COALESCE(p.api_gw_cost, 0) +
           COALESCE(p.fargate_total_cost, 0) + COALESCE(p.alb_total_cost, 0) as compute_cost
    FROM experiments e JOIN pricing p ON e.id = p.experiment_id;

    Note: Costs are calculated based on actual usage during the experiment,
    prorated to the experiment duration.
    """
    __tablename__ = "pricing"
    __table_args__ = (
        Index("idx_pricing_exp", "experiment_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False, unique=True,
        comment="Reference to parent experiment (one pricing record per experiment)"
    )

    # === Lambda costs (FaaS architecture only) ===
    lambda_total_invocations: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Total number of Lambda invocations during the experiment"
    )
    lambda_total_duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Sum of all Lambda execution durations in milliseconds"
    )
    lambda_total_gb_seconds: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Total GB-seconds consumed (duration_seconds * memory_gb)"
    )
    lambda_memory_gb: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Lambda memory configuration in GB (e.g., 0.5 for 512MB)"
    )
    lambda_request_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for Lambda requests ($0.20 per 1M requests after free tier)"
    )
    lambda_compute_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for Lambda compute (GB-seconds)"
    )
    lambda_total_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total Lambda cost = request_cost + compute_cost"
    )
    lambda_rate_request_per_million: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per million requests"
    )
    lambda_rate_per_gb_second: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(12, 10),
        comment="AWS rate: cost per GB-second of compute"
    )
    lambda_free_requests_per_month: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Free tier: requests included per month"
    )
    lambda_free_gb_seconds_per_month: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Free tier: GB-seconds included per month"
    )

    # === API Gateway costs (FaaS architecture only) ===
    api_gw_total_requests: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Total requests through API Gateway"
    )
    api_gw_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total API Gateway cost"
    )
    api_gw_rate_per_million: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per million API Gateway requests"
    )

    # === Fargate costs (ECS architectures only) ===
    fargate_task_cpu: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Fargate task CPU units (256, 512, 1024, etc.)"
    )
    fargate_task_memory_mb: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Fargate task memory in MB"
    )
    fargate_total_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total Fargate cost = vCPU cost + memory cost"
    )
    fargate_rate_vcpu_per_hour: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per vCPU-hour"
    )
    fargate_rate_memory_gb_per_hour: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per GB-hour of memory"
    )

    # === ALB costs (ECS architectures only) ===
    alb_duration_hours: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Duration ALB was running in hours"
    )
    alb_hourly_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Fixed hourly ALB cost"
    )
    alb_estimated_lcu: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Estimated Load Balancer Capacity Units consumed"
    )
    alb_lcu_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for LCU usage"
    )
    alb_total_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total ALB cost = hourly_cost + lcu_cost"
    )
    alb_rate_hourly: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: fixed cost per hour for ALB"
    )
    alb_rate_lcu_per_hour: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per LCU-hour"
    )

    # === Redis costs (all architectures) ===
    redis_instance_type: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="ElastiCache Redis instance type, e.g., 'cache.t3.micro'"
    )
    redis_duration_hours: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Duration Redis was running in hours"
    )
    redis_hourly_rate: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per hour for this instance type"
    )
    redis_total_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total Redis cost = duration_hours * hourly_rate"
    )

    # === Cognito costs (when auth is enabled) ===
    cognito_mau: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Cognito Monthly Active Users during experiment"
    )
    cognito_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cognito cost based on MAU pricing tiers"
    )
    cognito_rate_first_50k: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per MAU for first 50,000 users"
    )
    cognito_rate_next_50k: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per MAU for users 50,001-100,000"
    )
    cognito_rate_next_900k: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per MAU for users 100,001-1,000,000"
    )
    cognito_rate_over_1m: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="AWS rate: cost per MAU for users over 1,000,000"
    )
    cognito_note: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="Notes about Cognito pricing (e.g., free tier status)"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="pricing")


# =============================================================================
# PRICING COMPONENTS (Per-function/service breakdown)
# =============================================================================

class PricingComponent(Base):
    """
    Per-function (Lambda) or per-service (Fargate) cost breakdown.

    While the `pricing` table has aggregate costs, this table breaks down
    costs by individual Lambda function or ECS service.

    COMPONENT TYPES:
    - 'lambda_function': One row per Lambda function with invocation counts and costs
    - 'fargate_service': One row per ECS service with task hours and costs

    Use for identifying cost hotspots:
    SELECT component_name, total_cost
    FROM pricing_components
    WHERE experiment_id = ?
    ORDER BY total_cost DESC;
    """
    __tablename__ = "pricing_components"
    __table_args__ = (
        UniqueConstraint("experiment_id", "component_type", "component_name"),
        Index("idx_pricing_comp_exp", "experiment_id"),
        Index("idx_pricing_comp_type", "experiment_id", "component_type"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    component_type: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="Type of component: 'lambda_function' or 'fargate_service'"
    )
    component_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Name of the function or service: 'frontend', 'cart', 'products', etc."
    )

    # === Lambda function fields ===
    invocations: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Number of invocations of this Lambda function"
    )
    duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Total execution duration in milliseconds"
    )
    gb_seconds: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="GB-seconds consumed by this function"
    )
    request_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for requests to this function"
    )
    compute_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Compute cost (GB-seconds) for this function"
    )

    # === Fargate service fields ===
    task_cpu: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="CPU units allocated to tasks in this service"
    )
    task_memory_mb: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Memory in MB allocated to tasks in this service"
    )
    avg_running_tasks: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average number of running tasks during the experiment"
    )
    vcpu_hours: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Total vCPU-hours consumed"
    )
    memory_gb_hours: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Total memory GB-hours consumed"
    )
    vcpu_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for vCPU usage"
    )
    memory_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Cost for memory usage"
    )

    # === Common ===
    total_cost: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 6),
        comment="Total cost for this component"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="pricing_components")


# =============================================================================
# ECS METRICS (CloudWatch time-series)
# =============================================================================

class MetricsEcs(Base):
    """
    ECS service metrics time-series data from CloudWatch.

    ONLY POPULATED FOR ECS ARCHITECTURES (microservices, monolith).

    Contains periodic samples (typically 1-minute intervals) of:
    - CPU utilization
    - Memory utilization
    - Running/desired task counts (for auto-scaling analysis)

    Use for:
    - Analyzing resource utilization over time
    - Correlating scaling events with load changes
    - Identifying resource bottlenecks

    Example: Find periods of high CPU that might indicate scaling needs
    SELECT timestamp, service_name, cpu_percent, running_tasks
    FROM metrics_ecs
    WHERE experiment_id = ? AND cpu_percent > 80
    ORDER BY timestamp;
    """
    __tablename__ = "metrics_ecs"
    __table_args__ = (
        Index("idx_ecs_exp", "experiment_id"),
        Index("idx_ecs_exp_svc", "experiment_id", "service_name"),
        Index("idx_ecs_exp_ts", "experiment_id", "timestamp"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    service_name: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="ECS service name: 'frontend', 'cart', 'products', etc. For monolith: 'monolith'"
    )
    timestamp: Mapped[datetime] = mapped_column(
        nullable=False,
        comment="Timestamp of this metrics sample"
    )

    cpu_percent: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average CPU utilization percentage (0-100) across all tasks in the service"
    )
    memory_percent: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average memory utilization percentage (0-100) across all tasks"
    )
    running_tasks: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Number of tasks currently running (actual)"
    )
    desired_tasks: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Number of tasks desired by auto-scaler (may differ during scaling events)"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="metrics_ecs")


# =============================================================================
# ALB METRICS (CloudWatch time-series)
# =============================================================================

class MetricsAlb(Base):
    """
    Application Load Balancer metrics time-series data from CloudWatch.

    ONLY POPULATED FOR ECS ARCHITECTURES (microservices, monolith).

    Contains periodic samples of ALB performance:
    - Request counts and response times
    - HTTP status code distribution
    - Connection and health metrics

    Use for:
    - Understanding traffic patterns
    - Identifying error spikes
    - Correlating ALB metrics with application performance

    Note: For FaaS, similar metrics come from API Gateway (not stored separately).
    """
    __tablename__ = "metrics_alb"
    __table_args__ = (
        Index("idx_alb_exp", "experiment_id"),
        Index("idx_alb_exp_ts", "experiment_id", "timestamp"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    timestamp: Mapped[datetime] = mapped_column(
        nullable=False,
        comment="Timestamp of this metrics sample"
    )

    request_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Number of requests processed in this interval"
    )
    response_time_avg: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Average response time in seconds for this interval"
    )
    response_time_p95: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="95th percentile response time in seconds"
    )

    http_2xx_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Count of successful responses (200-299)"
    )
    http_4xx_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Count of client error responses (400-499)"
    )
    http_5xx_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="Count of server error responses (500-599)"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="metrics_alb")


# =============================================================================
# EDGE AUTH EVENTS (Lambda@Edge BEFAAS-EDGE instrumentation)
# =============================================================================

class EdgeAuthEvent(Base):
    """
    Structured events emitted by the edge-based authentication Lambda@Edge.

    ONLY POPULATED FOR 'edge' AND 'edge-selective' AUTH STRATEGIES, AND ONLY
    FOR EXPERIMENTS RUN WITH THE v2 (RUNTIME-JWKS-FETCH) EDGE LAMBDA. The
    legacy v1 variant (index.legacy-buildtime-jwks.js) emits no structured
    logs; see evaluation/bedrohung_der_validität.tex for context.

    EVENT TYPES
    -----------
    - 'authCheck'            One row per viewer-request. `outcome` classifies:
                             'success' (token verified + internal token signed),
                             'publicPassthrough' (non-protected path, no token),
                             'missingToken401' (protected path, no token),
                             'invalidToken401' (token verification failed).
                             Populates timing fields: total_ms, key_resolve_ms,
                             crypto_verify_ms, sign_ms. The per-request path
                             breakdown used for RQ2 edge-overhead analysis.
    - 'jwksFetch'            Logged ONCE per successful JWKS download on a
                             given execution-environment instance. `trigger`
                             is 'cold' (first fetch) or 'unknownKid' (rotation
                             refetch). Populates duration_ms, jwks_key_count,
                             jwks_fetch_number, instance_age_ms.
    - 'jwksFetchError'       Fetch failed (timeout, HTTP != 200, malformed).
                             Populates duration_ms, error.
    - 'jwksFetchPiggyback'   A concurrent caller joined an in-flight fetch.
                             Populates trigger.
    - 'jwksRefetchDebounced' An unknown kid was seen within the refetch debounce
                             window (JWKS_MIN_REFETCH_INTERVAL_MS). Populates
                             kid, since_last_ms.

    JOIN KEYS
    ---------
    - instance_id correlates all events from a single Lambda@Edge execution
      environment. Lets you reconstruct the per-instance JWKS-cache lifetime:
      first authCheck on that instance triggered the cold fetch; subsequent
      authChecks served from the cache.
    - lambda_request_id (from CloudWatch REPORT lines) joins to the
      lambda_executions table for edge functions.

    THREE-MODE CACHE DISTRIBUTION (used in chapter 6.3)
    ---------------------------------------------------
    - 'cached'     authCheck with triggered_jwks_fetch=false AND instance
                   already had a jwksFetch event before this request.
    - 'warm'       authCheck where the same kid is already in the cache
                   (distinguished from 'cached' only by instance age).
    - 'cold fetch' authCheck with triggered_jwks_fetch=true.

    Example query: fraction of requests that paid the JWKS fetch cost
        SELECT
            COUNT(*) FILTER (WHERE triggered_jwks_fetch) AS cold_count,
            COUNT(*) AS total
        FROM edge_auth_events
        WHERE experiment_id = ? AND event_type = 'authCheck' AND outcome = 'success';
    """
    __tablename__ = "edge_auth_events"
    __table_args__ = (
        Index("idx_edge_exp", "experiment_id"),
        Index("idx_edge_exp_event", "experiment_id", "event_type"),
        Index("idx_edge_exp_outcome", "experiment_id", "outcome"),
        Index("idx_edge_exp_instance", "experiment_id", "instance_id"),
        Index("idx_edge_exp_ts", "experiment_id", "timestamp_ms"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), nullable=False,
        comment="Reference to parent experiment"
    )

    # === Event identification ===
    event_type: Mapped[str] = mapped_column(
        String(30), nullable=False,
        comment="'authCheck' | 'jwksFetch' | 'jwksFetchError' | 'jwksFetchPiggyback' | 'jwksRefetchDebounced'"
    )
    instance_id: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="Per-execution-environment random ID (12 hex chars). Correlates all events from one warm Lambda@Edge replica."
    )
    lambda_request_id: Mapped[Optional[str]] = mapped_column(
        String(50),
        comment="AWS Lambda Request ID (joins with lambda_executions on edge Lambda)"
    )

    # === Timing ===
    timestamp_ms: Mapped[int] = mapped_column(
        BigInteger, nullable=False,
        comment="Unix timestamp (ms) when the event was emitted (Lambda-side Date.now())"
    )
    relative_time_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="Milliseconds since benchmark start"
    )
    now_perf_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="performance.now() value on the Lambda at emit time. Only meaningful within a single invocation."
    )

    # === authCheck fields ===
    uri: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="authCheck: request URI (path + query)"
    )
    outcome: Mapped[Optional[str]] = mapped_column(
        String(30),
        comment="authCheck: 'success' | 'publicPassthrough' | 'missingToken401' | 'invalidToken401'"
    )
    total_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="authCheck: end-to-end Lambda handler duration (performance.now()-based, excludes cold-start init)"
    )
    key_resolve_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="authCheck success: time spent resolving the Cognito signing key (0 on cache hit, ~1500ms on cold fetch)"
    )
    crypto_verify_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="authCheck success: time spent in crypto.verify() for the Cognito RSA signature"
    )
    sign_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="authCheck success: time spent Ed25519-signing the internal token"
    )
    triggered_jwks_fetch: Mapped[Optional[bool]] = mapped_column(
        Boolean,
        comment="authCheck success: true iff this request caused a JWKS fetch (cold instance or rotation refetch). Used for the three-mode distribution analysis."
    )
    instance_age_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="Milliseconds since this Lambda@Edge replica was booted (0 on cold start, increases on warm invocations)"
    )

    # === jwksFetch / jwksFetchError / jwksFetchPiggyback / jwksRefetchDebounced ===
    trigger: Mapped[Optional[str]] = mapped_column(
        String(20),
        comment="jwksFetch/Piggyback: 'cold' (first fetch on this instance) or 'unknownKid' (rotation refetch)"
    )
    duration_ms: Mapped[Optional[float]] = mapped_column(
        Float,
        comment="jwksFetch(Error): wall-clock time of the HTTPS request to the Cognito JWKS endpoint"
    )
    jwks_fetch_number: Mapped[Optional[int]] = mapped_column(
        Integer,
        comment="jwksFetch: monotonic counter (1 = first fetch on this instance, 2+ = rotation refetches)"
    )
    jwks_key_count: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="jwksFetch: number of keys returned by Cognito (typically 2)"
    )
    kid: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="jwksRefetchDebounced: the attacker-or-client-supplied kid that was rejected"
    )
    since_last_ms: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        comment="jwksRefetchDebounced: milliseconds since the previous JWKS fetch (less than JWKS_MIN_REFETCH_INTERVAL_MS = 5000)"
    )
    error: Mapped[Optional[str]] = mapped_column(
        Text,
        comment="jwksFetchError / authCheck(invalidToken401): error message"
    )

    # === Context enrichment (populated during import if possible) ===
    phase_index: Mapped[Optional[int]] = mapped_column(
        SmallInteger,
        comment="Benchmark phase index the event falls into (from timestamp → phase_starts mapping)"
    )
    phase_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        comment="Benchmark phase name"
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="edge_auth_events")


# =============================================================================
# DATABASE UTILITIES
# =============================================================================

def create_tables(engine):
    """Create all tables in the database."""
    Base.metadata.create_all(engine)


def drop_tables(engine):
    """Drop all tables from the database."""
    Base.metadata.drop_all(engine)


def add_table_comments(engine):
    """
    Add documentation comments to tables (PostgreSQL only).
    These comments are visible in database tools and help with schema discovery.
    """
    comments = {
        "schema_documentation": (
            "AI-readable documentation about the database schema and system. "
            "Query: SELECT * FROM schema_documentation ORDER BY sort_order; "
            "Categories: 'overview' (system context), 'concept' (key concepts), 'table' (table descriptions), 'query' (example queries)."
        ),
        "experiments": (
            "Master table for benchmark experiments. One row per experiment run. "
            "Join with other tables using experiment_id. "
            "Key fields: architecture (faas/microservices/monolith), auth_strategy (none/service-integrated/edge)."
        ),
        "requests": (
            "Client-side HTTP requests from Artillery load generator. "
            "PRIMARY TABLE for latency analysis. "
            "Key fields: latency_ms (end-to-end), is_error, x_pair (correlation ID). "
            "Filter by phase_name='baseline' for steady-state comparison."
        ),
        "handler_events": (
            "Server-side handler execution from BEFAAS instrumentation. "
            "Key fields: duration_ms (handler time), is_cold_start, x_pair (join with requests). "
            "Compare duration_ms across auth_strategy to measure auth overhead."
        ),
        "lambda_executions": (
            "Lambda platform metrics from CloudWatch REPORT logs. FaaS only. "
            "Key fields: billed_duration_ms (what you pay), init_duration_ms (cold start), is_cold_start. "
            "Join with handler_events on request_id=lambda_request_id."
        ),
        "rpc_calls": (
            "Inter-function/service calls within a request. "
            "direction='out': outgoing call (has duration_ms, target_function). "
            "direction='in': incoming call (has is_cold_start). "
            "Use call_x_pair to trace downstream calls."
        ),
        "pricing": (
            "Aggregated cost data per experiment. "
            "Contains Lambda, API Gateway, Fargate, ALB, Redis, Cognito costs. "
            "FaaS uses lambda_* and api_gw_* fields. ECS uses fargate_* and alb_* fields."
        ),
        "phases": (
            "Benchmark load phases: 'warmup' (initialize), 'baseline' (steady state), 'stress' (high load). "
            "Use phase_name in WHERE clauses for fair comparisons."
        ),
        "metrics_ecs": (
            "ECS CloudWatch metrics time-series. Microservices/monolith only. "
            "Track CPU/memory utilization and task counts for auto-scaling analysis."
        ),
        "metrics_alb": (
            "ALB CloudWatch metrics time-series. ECS architectures only. "
            "Track request counts, response times, and HTTP status distribution."
        ),
        "edge_auth_events": (
            "Structured BEFAAS-EDGE events from the edge-based authentication Lambda@Edge. "
            "Populated only for auth_strategy in ('edge','edge-selective') AND experiments using the v2 runtime-JWKS-fetch variant. "
            "event_type: authCheck (per-request timing), jwksFetch (cache-fill), jwksFetchError, jwksFetchPiggyback, jwksRefetchDebounced. "
            "Use triggered_jwks_fetch to classify requests into the cached/warm/cold three-mode distribution."
        ),
    }

    with engine.connect() as conn:
        for table, comment in comments.items():
            try:
                conn.execute(text(f"COMMENT ON TABLE {table} IS :comment"), {"comment": comment})
                conn.commit()
            except Exception:
                pass  # SQLite doesn't support COMMENT


def add_column_comments(engine):
    """
    Add documentation comments to all columns (PostgreSQL only).
    This ensures comments are set even if SQLAlchemy didn't apply them during table creation.
    """
    # Collect all column comments from the models
    column_comments = {}
    for mapper in Base.registry.mappers:
        table_name = mapper.local_table.name
        column_comments[table_name] = {}
        for column in mapper.local_table.columns:
            if column.comment:
                column_comments[table_name][column.name] = column.comment

    with engine.connect() as conn:
        for table_name, columns in column_comments.items():
            for column_name, comment in columns.items():
                try:
                    conn.execute(
                        text(f'COMMENT ON COLUMN {table_name}.{column_name} IS :comment'),
                        {"comment": comment}
                    )
                except Exception:
                    pass  # SQLite doesn't support COMMENT
        conn.commit()


def get_schema_documentation() -> str:
    """
    Generate comprehensive schema documentation as a string.
    Useful for providing context to AI systems querying the database.
    """
    doc = '''
================================================================================
BEFAAS BENCHMARK DATABASE SCHEMA DOCUMENTATION
================================================================================

This database stores results from load testing experiments comparing cloud
architectures (FaaS/Lambda, Microservices/ECS, Monolith/ECS) with different
authentication strategies.

================================================================================
KEY CONCEPTS
================================================================================

EXPERIMENT: A single benchmark run with specific architecture + auth + hardware.
  - architecture: 'faas' (Lambda), 'microservices' (ECS multi), 'monolith' (ECS single)
  - auth_strategy: 'none', 'service-integrated' (JWT in handler), 'edge' (gateway auth)

CORRELATION IDs:
  - x_pair: Links client request -> server handler -> RPC calls
  - lambda_request_id: Links handler_events -> lambda_executions

PHASES: Benchmark stages with different load patterns
  - 'warmup': Initialize cold containers (exclude from perf analysis)
  - 'baseline': Steady-state load (USE THIS for fair comparisons)
  - 'stress'/'ramp': Variable load patterns

================================================================================
TABLE RELATIONSHIPS
================================================================================

experiments (1) ──┬── (N) requests           # Client HTTP requests
                  ├── (N) handler_events     # Server handler executions
                  ├── (N) lambda_executions  # Lambda platform metrics [FaaS only]
                  ├── (N) container_starts   # Cold start events
                  ├── (N) rpc_calls          # Inter-service calls
                  ├── (N) phases             # Benchmark phase definitions
                  ├── (N) scaling_rules      # ECS auto-scaling config
                  ├── (1) pricing            # Aggregated costs
                  ├── (N) pricing_components # Per-function/service costs
                  ├── (N) metrics_ecs        # ECS time-series [ECS only]
                  └── (N) metrics_alb        # ALB time-series [ECS only]

================================================================================
MAIN TABLES
================================================================================

EXPERIMENTS - Master table, one row per benchmark run
  Key columns: architecture, auth_strategy, ram_in_mb, run_timestamp
  Use: Filter/group experiments for comparison

REQUESTS - Client-side HTTP requests (PRIMARY for latency analysis)
  Key columns: latency_ms, is_error, is_timeout, x_pair, phase_name, endpoint
  Use: Percentile latency, error rates, throughput analysis
  Join: handler_events ON x_pair for server-side correlation

HANDLER_EVENTS - Server-side handler execution
  Key columns: duration_ms, is_cold_start, x_pair, function_name, route
  Use: Server processing time, auth overhead analysis
  Join: requests ON x_pair, lambda_executions ON lambda_request_id

LAMBDA_EXECUTIONS - Lambda platform metrics [FaaS only]
  Key columns: billed_duration_ms, init_duration_ms, is_cold_start, memory_size_mb
  Use: Cold start analysis, Lambda cost calculation

RPC_CALLS - Inter-service calls within a request
  Key columns: direction ('in'/'out'), function_name, target_function, duration_ms
  Use: Call graph analysis, inter-service latency

PRICING - Aggregated costs per experiment
  Key columns: lambda_total_cost, fargate_total_cost, alb_total_cost
  Use: Cost comparison between architectures

================================================================================
COMMON QUERIES
================================================================================

-- Compare latency across architectures (baseline phase only):
SELECT e.architecture, e.auth_strategy,
       percentile_cont(0.5) WITHIN GROUP (ORDER BY r.latency_ms) as p50,
       percentile_cont(0.95) WITHIN GROUP (ORDER BY r.latency_ms) as p95,
       percentile_cont(0.99) WITHIN GROUP (ORDER BY r.latency_ms) as p99
FROM requests r
JOIN experiments e ON r.experiment_id = e.id
WHERE r.phase_name = 'baseline' AND NOT r.is_error
GROUP BY e.architecture, e.auth_strategy;

-- Auth overhead (compare handler time with/without auth):
SELECT e.auth_strategy,
       AVG(h.duration_ms) as avg_handler_ms,
       percentile_cont(0.95) WITHIN GROUP (ORDER BY h.duration_ms) as p95_handler_ms
FROM handler_events h
JOIN experiments e ON h.experiment_id = e.id
WHERE h.phase_name = 'baseline'
GROUP BY e.auth_strategy;

-- Cold start analysis for Lambda:
SELECT function_name,
       COUNT(*) FILTER (WHERE is_cold_start) as cold_starts,
       COUNT(*) as total_invocations,
       AVG(init_duration_ms) FILTER (WHERE is_cold_start) as avg_init_ms
FROM lambda_executions
WHERE experiment_id = ?
GROUP BY function_name;

-- Cost comparison:
SELECT e.architecture, e.auth_strategy,
       COALESCE(p.lambda_total_cost, 0) + COALESCE(p.api_gw_cost, 0) +
       COALESCE(p.fargate_total_cost, 0) + COALESCE(p.alb_total_cost, 0) as compute_cost,
       p.redis_total_cost
FROM experiments e
LEFT JOIN pricing p ON e.id = p.experiment_id;

-- Error rate by endpoint:
SELECT endpoint,
       COUNT(*) as total,
       COUNT(*) FILTER (WHERE is_error) as errors,
       ROUND(100.0 * COUNT(*) FILTER (WHERE is_error) / COUNT(*), 2) as error_pct
FROM requests
WHERE experiment_id = ?
GROUP BY endpoint
ORDER BY error_pct DESC;

================================================================================
QUERYING SCHEMA COMMENTS IN POSTGRESQL
================================================================================

-- Get table comments:
SELECT c.relname as table_name, d.description
FROM pg_class c
JOIN pg_description d ON c.oid = d.objoid AND d.objsubid = 0
WHERE c.relkind = 'r' AND c.relnamespace = 'public'::regnamespace;

-- Get column comments for a specific table:
SELECT a.attname as column_name, d.description
FROM pg_attribute a
JOIN pg_class c ON a.attrelid = c.oid
LEFT JOIN pg_description d ON a.attrelid = d.objoid AND a.attnum = d.objsubid
WHERE c.relname = 'requests' AND a.attnum > 0 AND NOT a.attisdropped;

-- Get all column comments:
SELECT c.relname as table_name, a.attname as column_name, d.description
FROM pg_attribute a
JOIN pg_class c ON a.attrelid = c.oid
LEFT JOIN pg_description d ON a.attrelid = d.objoid AND a.attnum = d.objsubid
WHERE c.relkind = 'r' AND c.relnamespace = 'public'::regnamespace
  AND a.attnum > 0 AND NOT a.attisdropped AND d.description IS NOT NULL
ORDER BY c.relname, a.attnum;

================================================================================
'''
    return doc