#!/usr/bin/env python3
"""Generate edge_selective_summary_table.tex for tab:edge-selective-summary.

Aggregated comparison Edge-Selective vs Full-Edge: ΔP50 and ΔP99 per
(architecture, hw) configuration.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import numpy as np
import pandas as pd
from db_connection import query_df, PLOT_DIR, EXCLUDE_SQL


def hw_label(arch, ram, cpu):
    if arch == 'faas':
        return f"{ram}MB"
    return {0.25: 'S', 0.5: 'M', 1.0: 'L', 4.0: 'XL'}.get(float(cpu), f"{cpu}vCPU")


def hw_tex(arch, hw):
    if arch == 'faas':
        ram = hw.replace('MB', '')
        return rf"\ac{{FaaS}} {int(ram):,}\,MB".replace(',', '.')
    prefix = {'microservices': 'MS', 'monolith': 'Monolith'}.get(arch, arch)
    return f"{prefix} {hw}"


def main():
    edge_sel = query_df(f"""
        SELECT e.architecture, e.auth_strategy,
               e.ram_in_mb, COALESCE(e.cpu_in_vcpu, 0) AS cpu,
               percentile_cont(0.50) WITHIN GROUP (ORDER BY r.latency_ms)
                   FILTER (WHERE NOT r.is_error) AS p50,
               percentile_cont(0.99) WITHIN GROUP (ORDER BY r.latency_ms)
                   FILTER (WHERE NOT r.is_error) AS p99
        FROM experiments e
        JOIN requests r ON r.experiment_id = e.id
        WHERE {EXCLUDE_SQL}
          AND e.auth_strategy IN ('edge', 'edge-selective')
          AND r.phase_name = 'Baseline'
        GROUP BY e.architecture, e.auth_strategy, e.ram_in_mb, cpu
        HAVING COUNT(*) FILTER (WHERE NOT r.is_error) > 1000
    """)
    if edge_sel.empty:
        print('No data'); return

    for col in ['p50', 'p99']:
        edge_sel[col] = edge_sel[col].astype(float)
    edge_sel['hw'] = edge_sel.apply(
        lambda r: hw_label(r['architecture'], r['ram_in_mb'], r['cpu']), axis=1)

    lines = []
    lines.append("% Auto-generated by tables/tab_edge_selective_summary.py.")
    lines.append(r"\begin{table}[htbp]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{3pt}")
    lines.append(r"\caption{Aggregierter Vergleich über alle Endpunkte: Edge-Selective vs.\ "
                 r"Full-Edge. $\Delta_{\text{ES-FE}} = P_q(\text{Edge-Selective}) - "
                 r"P_q(\text{Full-Edge})$; negative Werte bedeuten eine niedrigere "
                 r"Latenz durch Edge-Selective.}")
    lines.append(r"\label{tab:edge-selective-summary}")
    lines.append(r"\begin{tabular}{@{}l S[table-format=+3.0] S[table-format=+3.0]@{}}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Konfiguration} & {$\boldsymbol{\Delta_{\mathrm{ES-FE}}}$ "
                 r"\textbf{P50}} & {$\boldsymbol{\Delta_{\mathrm{ES-FE}}}$ \textbf{P99}} \\")
    lines.append(r"\midrule")

    arch_order = ['faas', 'microservices', 'monolith']
    first_arch = True
    for arch in arch_order:
        arch_data = edge_sel[edge_sel['architecture'] == arch]
        if arch_data.empty:
            continue
        if not first_arch:
            lines.append(r"\midrule")
        first_arch = False

        hw_order = sorted(arch_data['hw'].unique(),
                          key=lambda x: {'S': 1, 'M': 2, 'L': 3, 'XL': 4}.get(x,
                              int(x.replace('MB', '')) if 'MB' in x else 0))

        for hw in hw_order:
            es = arch_data[(arch_data['hw'] == hw) & (arch_data['auth_strategy'] == 'edge-selective')]
            fe = arch_data[(arch_data['hw'] == hw) & (arch_data['auth_strategy'] == 'edge')]
            if es.empty or fe.empty:
                continue
            dp50 = es.iloc[0]['p50'] - fe.iloc[0]['p50']
            dp99 = es.iloc[0]['p99'] - fe.iloc[0]['p99']
            tex = hw_tex(arch, hw)
            lines.append(f"{tex} & {dp50:+.0f} & {dp99:+.0f} \\\\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\setlength{\tabcolsep}{6pt}")
    lines.append(r"\end{table}")

    path = f"{PLOT_DIR}/edge_selective_summary_table.tex"
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Saved: {path}")


if __name__ == '__main__':
    main()
