#!/usr/bin/env python3
"""Generate cost_latency_tradeoff.pdf for fig:cost-latency-tradeoff.

The cost axis is read from cost_per_experiment.csv, which is generated by
tables/tab_cost_per_1m.py from raw measurement tables. This script therefore
does not use the precomputed pricing table.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from db_connection import query_df, PLOT_DIR, EXCLUDE_SQL, ARCH_COLORS

AUTH_MARKERS = {
    'None': 'o',
    'Cognito': 's',
    'Manual (bcrypt)': '^',
    'Edge': 'D',
    'Edge-Sel.': 'P',
}
X_CLIP = 8000


def main():
    cost_path = os.path.join(PLOT_DIR, 'cost_per_experiment.csv')
    if not os.path.exists(cost_path):
        raise SystemExit(f'Missing {cost_path}; run tables/tab_cost_per_1m.py first.')

    costs = pd.read_csv(cost_path)
    costs = costs[costs['auth_label'] != 'Manual (argon2id)'].copy()
    costs = costs.drop(columns=['p50', 'p99'], errors='ignore')

    perf = query_df(f"""
        SELECT
            e.id,
            percentile_cont(0.99) WITHIN GROUP (ORDER BY r.latency_ms)
                FILTER (WHERE NOT r.is_error) AS p99
        FROM experiments e
        JOIN requests r ON r.experiment_id = e.id
        WHERE {EXCLUDE_SQL}
          AND e.password_hash_algorithm IS DISTINCT FROM 'argon2id'
        GROUP BY e.id
        HAVING COUNT(*) > 50000
    """)

    if costs.empty or perf.empty:
        print('No data'); return

    perf['p99'] = perf['p99'].astype(float)
    merged = costs.merge(perf, on='id', how='inner')
    merged['cost_per_1M_successful'] = merged['cost_per_1M_successful'].replace([np.inf, -np.inf], np.nan)

    cost_avg = merged.groupby(['architecture', 'auth_label', 'hw', 'ram_in_mb', 'cpu_in_vcpu']).agg(
        mean_cost_per_1M=('cost_per_1M_successful', 'mean'),
        mean_p99=('p99', 'mean'),
    ).reset_index()

    plot_data = cost_avg[cost_avg['mean_p99'] <= X_CLIP].copy()
    n_excluded = len(cost_avg) - len(plot_data)

    fig, ax = plt.subplots(figsize=(12, 7))

    for _, r in plot_data.iterrows():
        color = ARCH_COLORS.get(r['architecture'], '#999')
        marker = AUTH_MARKERS.get(r['auth_label'], 'o')
        ax.scatter(r['mean_p99'], r['mean_cost_per_1M'],
                   c=color, marker=marker, s=120, alpha=0.85,
                   edgecolors='black', linewidths=0.5)

    points = plot_data[['mean_p99', 'mean_cost_per_1M']].dropna().values
    if len(points) > 0:
        pareto = []
        for i, (lat, cost) in enumerate(points):
            dominated = False
            for j, (lat2, cost2) in enumerate(points):
                if i != j and lat2 <= lat and cost2 <= cost and (lat2 < lat or cost2 < cost):
                    dominated = True
                    break
            if not dominated:
                pareto.append(i)
        if pareto:
            pareto_points = points[pareto]
            pareto_sorted = pareto_points[pareto_points[:, 0].argsort()]
            ax.plot(pareto_sorted[:, 0], pareto_sorted[:, 1], 'k--', alpha=0.4,
                    linewidth=1.5, label='Pareto frontier')

    legend_elements = []
    for arch, color in ARCH_COLORS.items():
        legend_elements.append(Line2D([0], [0], marker='o', color='w',
                                       markerfacecolor=color, markersize=10, label=arch))
    for auth, marker in AUTH_MARKERS.items():
        legend_elements.append(Line2D([0], [0], marker=marker, color='w',
                                       markerfacecolor='gray', markersize=10, label=auth))
    legend_elements.append(Line2D([0], [0], linestyle='--', color='black',
                                   alpha=0.4, label='Pareto frontier'))
    ax.legend(handles=legend_elements, loc='upper right', fontsize=9)

    ax.set_xlabel('P99 latency (ms)')
    ax.set_ylabel('Cost per 1M successful requests (USD)')
    excluded_note = f'\n({n_excluded} configs with P99 > {X_CLIP}ms excluded)' if n_excluded else ''
    ax.set_title(f'Cost-latency trade-off{excluded_note}', fontweight='bold')
    ax.grid(alpha=0.3)
    ax.set_xlim(left=-50)

    plt.tight_layout()
    path = f"{PLOT_DIR}/cost_latency_tradeoff.pdf"
    fig.savefig(path, bbox_inches='tight')
    print(f"Saved: {path}")
    plt.close()


if __name__ == '__main__':
    main()
